name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 19"
        uses: actions/setup-node@v2
        with:
          node-version: "19.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: "Version and publish" # Interesting step
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = develop ]; then
            yarn lerna version --conventional-commits --conventional-prerelease --preid beta --yes --no-private
          else
            yarn lerna version --conventional-commits --conventional-graduate --yes --no-private
          fi

          yarn lerna publish from-git --yes --no-private
